"""empty message

Revision ID: 98a6c5b0a1ae
Revises: 
Create Date: 2018-10-20 14:31:59.483734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98a6c5b0a1ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('turbo', sa.SmallInteger(), nullable=True))
    op.drop_column('plan', 'MonthStartDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('MonthStartDate', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('plan', 'turbo')
    # ### end Alembic commands ###
